//! # Router Module
//!
//! This module provides the core traits and types for the routing system in Moonbeam.
//!
//! It includes:
//! - `RouteHandler`: A trait for types that can handle HTTP requests within a router.
//! - `PathParams`: A wrapper for extracting named path parameters from the URL.
//! - `FromParams`: A trait for converting raw path parameters into strongly-typed values.
//!
//! The routing system is designed to be used with the `#[route]` and `router!` macros
//! provided by the `moonbeam` crate (via `moonbeam-attributes`).

mod path_params;
pub use path_params::{FromParams, PathParams};

use crate::http::{Body, Request, Response};
use std::future::Future;

/// Trait implemented by route handlers generated by the `#[route]` macro.
///
/// This trait defines the interface for handling requests with support for:
/// - Path parameters (e.g., `/users/:id`)
/// - Rest parameters (e.g., `/static/*path`)
/// - Application state injection
///
/// Implementations of this trait are typically generated automatically by the `#[route]` macro.
pub trait RouteHandler<S>: 'static {
	/// Handles an incoming HTTP request.
	///
	/// # Arguments
	///
	/// * `req` - The incoming HTTP request.
	/// * `params` - A slice of path parameter values extracted from the URL.
	/// * `state` - A reference to the application state.
	fn call<'a, 'b>(
		&self,
		req: Request<'a, 'b>,
		params: &'_ [&'b str],
		state: &'static S,
	) -> impl Future<Output = impl Into<Response>>;
}

impl Into<Response> for () {
	fn into(self) -> Response {
		Response::empty()
	}
}

impl Into<Response> for Body {
	fn into(self) -> Response {
		Response::new_with_body(self, None)
	}
}

impl Into<Response> for (Body, Option<&str>) {
	fn into(self) -> Response {
		Response::new_with_body(self.0, self.1)
	}
}

impl<T: Into<Response>> Into<Response> for Option<T> {
	fn into(self) -> Response {
		match self {
			Some(val) => val.into(),
			None => Response::not_found(),
		}
	}
}

impl<T: Into<Response>, E: Into<Response>> Into<Response> for Result<T, E> {
	fn into(self) -> Response {
		match self {
			Ok(val) => val.into(),
			Err(err) => err.into(),
		}
	}
}
