mod path_params;
pub use path_params::{FromParams, ParamMap, PathParams, PathParamsMap};

use crate::http::{Request, Response};
use std::collections::HashMap;
use std::future::Future;

/// Trait implemented by route handlers generated by the `#[route]` macro.
pub trait RouteHandler<S>: 'static {
	fn call<'a, 'b>(
		&self,
		req: Request<'a, 'b>,
		params: HashMap<&'b str, &'b str>,
		state: &'static S,
	) -> impl Future<Output = Response>;
}
